title: Mohit Kumar Jaiswal
url: "https://github.com/mohitkumarjaiswal"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "cv"
 - name: "Contact"
   link: "contact"
